### PR TITLE
Added failing tests for lists with tabs

### PR DESCRIPTION
**Pull request by onigoetz**
Hi,

A user of a project I work on reported me an issue about not being able to use tabs in lists anymore. (justinwalsh/daux.io#376)

I can confirm that it is currently the case, as you can see with the tests I added to this Pull Request.

The test fails with : 
```diff
--- Expected
+++ Actual
@@ @@
 <li>foo
-<ul>
-<li>bar</li>
-</ul>
-</li>
+       * bar</li>
 </ul>
 <hr />
 <hr />
 <ul>
 <li>foo
 <ul>
 <li>bar</li>
 </ul>
 </li>
 </ul>
 '
```

I would really like to help and contribute a fix but I'm afraid I really have no idea where to start looking for.

From what I was able to track down, the feature is broken since the Pull Request #234 was merged.

### CODE REVIEW

**Comment by onigoetz** [comment]
@colinodell Do you have an idea how we could fix this ?

**Comment by colinodell** [comment]
Sorry for the delay in responding to this - it must've slipped through my inbox.  I'll take a look at this tonight or tomorrow.

**Comment by colinodell** [comment]
I figured out the issue.  One of the parsers was performing some operations on the `Cursor` and then tried to restore it to its original state.  However, when saving/restoring the state, **I totally forgot to include an important variable that tracks tab indentation**.  As a result, the `Cursor` was never restored to the proper state which caused some indentation issues.

I resolved the issue (see 4c625f3) and merged it into `master`.  I then rebased your regression tests onto `master` via 75e0e68.  The failing tests you submitted are now passing.

Thanks for your help and patience!

Fixed; closed.

**Comment by onigoetz** [comment]
This is awesome, thank you :D

Get Outlook for iOS




On Sun, Aug 28, 2016 at 5:31 PM +0200, "colinodell" <notifications@github.com> wrote:












I figured out the issue.  One of the parsers was performing some operations on the Cursor and then tried to restore it to its original state.  However, when saving/restoring the state, I totally forgot to include an important variable that tracks tab indentation.  As a result, the Cursor was never restored to the proper state which caused some indentation issues.



I resolved the issue (see 4c625f3) and merged it into master.  I then rebased your regression tests onto master via 75e0e68.  The failing tests you submitted are now passing.



Thanks for your help and patience!



Fixed; closed.

**Pull request closed without merging**
