### PR TITLE
Added support for tag attributes in renderers

### PR DESCRIPTION
**Pull request by hason**
I would like to implement special attributes extension and this PR would help me greatly.

### CODE REVIEW

**Comment by colinodell** [comment]
Thanks for submitting this!

The ability to define arbitrary HTML attributes [has come up before](https://github.com/thephpleague/commonmark/issues/32#issuecomment-68006068), and your solution almost exactly matches my second idea :)  I still have the same reservations about using this approach though.

I wonder if we should modify rendering to be more event-based, or perhaps just add a generic post-render event.  You'd have some custom code listening for an event.  You'd receive the original block/inline and the resulting `HtmlElement`, allowing you to add whatever attributes you'd like.

[kzykhys/ciconia](https://github.com/kzykhys/Ciconia) uses event emitters, which seems interesting.  I've never worked with them before, but perhaps it's worth investigating whether this library should use that approach instead.

**Comment by colinodell** [comment]
Maybe we could implement (or at least enable) something like the decorator functionality used by [Stack](http://stackphp.com/)?  That might also enable #35 too.

I haven't thought too deeply about this, but the idea seems intriguing enough to possibly try.

**Comment by hason** [comment]
Your suggestion about decorator could be solved also via #106. The renderer is a special case of a node visitor (see https://github.com/arnaud-lb/MtHaml/blob/master/lib/MtHaml/NodeVisitor/RendererAbstract.php).

**Comment by hason** [comment]
In CommonMark Attributes Extension I have created custom html renderer https://github.com/webuni/commonmark-attributes-extension/blob/master/src/HtmlRenderer.php. I wanted to created it as a decorator, but unsuccessfully.

**Comment by colinodell** [comment]
@hason does the commonmark-attributes-extension package solve your need, meaning we can close this?

**Comment by colinodell** [comment]
I'm going to close this for now, but we can certainly reopen it later if needed.

**Comment by colinodell** [comment]
I've decided to re-open this, as there does still seem to be a need for this functionality (see #145).  I'm also warming up to this idea the more I think about it.

While I do like this approach and how it works, I [still wonder whether an alternate event-oriented approach would be better](https://github.com/thephpleague/commonmark/pull/101#issuecomment-106026529).  That would require significant changes though, so maybe we should use the proposed solution for now and revisit this later?

**Comment by colinodell** [comment]
Closing in favor of #165, which is identical (but with merge conflicts resolved).

**Pull request closed without merging**
