### PR TITLE
Resolve parent class

### PR DESCRIPTION
**Pull request by colinodell**
Implements #209

### CODE REVIEW

**Comment by colinodell** [comment]
@marijnvdwerf Would you mind reviewing this when you get a chance? Thanks!

**Comment by hason** [comment]
@colinodell What is status of this PR?

**Comment by colinodell** [comment]
I was waiting to see if @marijnvdwerf (or anyone else who might need it) had any feedback on this change.  Once someone says "yes, this looks good and will suit my needs" I'll happily resolve the conflict and merge the change in - I just don't want to spend time on something that won't be useful.

**Comment by m1guelpf** [comment]
@colinodell What's the status of this?

**Comment by colinodell** [comment]
@m1guelpf Status is the same as before. I am waiting for feedback on this feature - either from people who want it or from anyone who dislikes the feature.

**Comment by marijnvdwerf** [comment]
Shit, completely forgot to reply on this since I was busy with uni! Apologies for that.

The project I wanted to use this on has unfortunately been cancelled, so I don't have a use for the feature anymore.

**Comment by colinodell** [comment]
Closing for now - will re-open if anyone expresses a need for it in the future.

**Pull request merged**
