### PR TITLE
Change auto-prefixing to a secure protocol

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Hmmm, github spec wants http. :/

**Comment by colinodell** [comment]
We could introduce a config option for this

**Comment by GrahamCampbell** [comment]
We could report this as a security vulnerability to GitHub. Surely this introduces a man in the middle vulnerability. If people need http, they should probably explicitly say it. ;)

**Comment by colinodell** [comment]
I agree that `https` should be the default, and an issue has been opened on the GFM library proposing exactly that: https://github.com/github/cmark-gfm/issues/98

Unless/until the spec is updated accordingly, I think we should keep this library as-is, or at least make the default scheme configurable.

**Comment by colinodell** [comment]
Closing this in favor of #987

**Pull request closed without merging**
