### PR TITLE
Do not run RIPS in PRs

### PR DESCRIPTION
**Pull request by szepeviktor**
Thank you @GrahamCampbell https://github.com/thephpleague/commonmark/pull/390#issuecomment-561327236

docs https://docs.travis-ci.com/user/environment-variables/#default-environment-variables

### CODE REVIEW

**Comment by szepeviktor** [comment]
A better solution would be something like https://docs.travis-ci.com/user/conditional-builds-stages-jobs/

**Comment by GrahamCampbell** [comment]
Is it possible to switch on if a variable is set?

**Comment by GrahamCampbell** [comment]
Oh, you can do if on `type`.

**Comment by GrahamCampbell** [comment]
https://docs.travis-ci.com/user/conditions-v1

**Comment by szepeviktor** [comment]
Done.

I've left the long if broken into multiple lines for readability.

**Comment by GrahamCampbell** [comment]
👍

**Comment by szepeviktor** [comment]
_suddenly_ missing from the job list 

kép

**Comment by colinodell** [comment]
This is awesome, thank you so much!

**Comment by szepeviktor** [comment]
You're welcome.

**Pull request merged**
