### PR TITLE
memory usage

### PR DESCRIPTION
**Pull request by krakjoe**
* improve usage errors
  * optionally collect memory usage stats from isolated processes

I think I'm done now ... sorry about noise ...

### CODE REVIEW

**Comment by colinodell** [comment]
> sorry about noise ...

Not a problem, these changes are very helpful!

**Comment by krakjoe** [comment]
Just noticed, set `$position = 1;` in `$display` ...

**Comment by colinodell** [comment]
I'll fix that directly on master, one sec :)

**Comment by colinodell** [comment]
Fixed via dc4f98c. Thanks again!

**Pull request merged**
