### PR TITLE
Added reference to parent block for inline elements before processing

### PR DESCRIPTION
**Pull request by hason**
I want to solve a hack with ``debug_backtrace`` in https://github.com/webuni/commonmark-attributes-extension/blob/master/src/AttributesInlineProcessor.php#L39

### CODE REVIEW

**Comment by colinodell** [comment]
Aren't we already setting the parent of these inlines inside the [setInlines() method](https://github.com/thephpleague/commonmark/blame/master/src/Block/Element/AbstractInlineContainer.php#L57-59)?

**Comment by colinodell** [comment]
I'd prefer only setting the parent relationship once.

Also, I don't really like how we have to modify two methods to pass this information into `InlineParserEngine::processInlines`.  Perhaps we should pass it as part of the `InlineParserContext` instead.  Or maybe there's a different/better way to achieve what you're looking for?

**Comment by hason** [comment]
My problem would be solved by implementing the visitor patter as I suggested in #106.

**Comment by colinodell** [comment]
Closing this in favor of #162.  It's basically the same approach, just done slightly differently.  Thanks for providing the idea!

**Pull request closed without merging**
