### PR TITLE
Bugfix/windows bin

### LINKED ISSUE #189: Tests failing on Windows PHP 5.6.13
Hello,

7 of the tests are failing under PHP 5.6.13 for Windows. I cloned the repository, ran `composer install` and then `phpunit`. This may be related, but in addition, if I run `php bin\commonmark`, nothing seems to happen (I have to CTRL-C out of PHP).

Results:

```shell
C:\inetpub\commonmark>phpunit
PHPUnit 4.7.7 by Sebastian Bergmann and contributors.

Runtime:        PHP 5.6.13 with Xdebug 2.3.2
Configuration:  C:\inetpub\commonmark\phpunit.xml.dist

FFFFFFF.......................................................  62 / 956 (  6%)
.............................................................. 124 / 956 ( 12%)
.............................................................. 186 / 956 ( 19%)
.............................................................. 248 / 956 ( 25%)
.............................................................. 310 / 956 ( 32%)
.............................................................. 372 / 956 ( 38%)
.............................................................. 434 / 956 ( 45%)
.............................................................. 496 / 956 ( 51%)
.............................................................. 558 / 956 ( 58%)
.............................................................. 620 / 956 ( 64%)
.............................................................. 682 / 956 ( 71%)
.............................................................. 744 / 956 ( 77%)
.............................................................. 806 / 956 ( 84%)
.............................................................. 868 / 956 ( 90%)
.............................................................. 930 / 956 ( 97%)
..........................

Time: 3.43 minutes, Memory: 47.00Mb

There were 7 failures:

1) League\CommonMark\Tests\Functional\BinTest::testNoArgsOrStdin
Failed asserting that 'Failed without error message: C:\inetpub\commonmark\bin\commonmark' contains "Usage:".

C:\inetpub\commonmark\tests\functional\BinTest.php:19

2) League\CommonMark\Tests\Functional\BinTest::testHelpShortFlag
Failed asserting that 1 matches expected 0.

C:\inetpub\commonmark\tests\functional\BinTest.php:31

3) League\CommonMark\Tests\Functional\BinTest::testHelpOption
Failed asserting that 1 matches expected 0.

C:\inetpub\commonmark\tests\functional\BinTest.php:44

4) League\CommonMark\Tests\Functional\BinTest::testUnknownOption
Failed asserting that 'Failed without error message: C:\inetpub\commonmark\bin\commonmark --foo' contains "Unknown option".

C:\inetpub\commonmark\tests\functional\BinTest.php:58

5) League\CommonMark\Tests\Functional\BinTest::testFileArgument
Failed asserting that 1 matches expected 0.

C:\inetpub\commonmark\tests\functional\BinTest.php:70

6) League\CommonMark\Tests\Functional\BinTest::testStdin
Failed asserting that 1 matches expected 0.

C:\inetpub\commonmark\tests\functional\BinTest.php:83

7) League\CommonMark\Tests\Functional\LocalDataTest::testExample with data set #0 ('# H1\n\n## H2\n\n### H3\n\n#### H4\n...#####\n', '<h1>H1</h1>\n<h2>H2</h2>\n<h3>H...</h6>\n', 'atx_header')
Unexpected result for "atx_header" test
=== markdown ===============
# H1

## H2

### H3

#### H4

##### H5

###### H6

# H1 #

## H2 ##

### H3 ###

#### H4 ####

##### H5 #####

###### H6 ######

=== expected ===============
<h1>H1</h1>
<h2>H2</h2>
<h3>H3</h3>
<h4>H4</h4>
<h5>H5</h5>
<h6>H6</h6>
<h1>H1</h1>
<h2>H2</h2>
<h3>H3</h3>
<h4>H4</h4>
<h5>H5</h5>
<h6>H6</h6>

=== got ====================
<h1>H1</h1>
<h2>H2</h2>
<h3>H3</h3>
<h4>H4</h4>
<h5>H5</h5>
<h6>H6</h6>
<h1>H1</h1>
<h2>H2</h2>
<h3>H3</h3>
<h4>H4</h4>
<h5>H5</h5>
<h6>H6</h6>

Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
 '<h1>H1</h1>
 <h2>H2</h2>
 <h3>H3</h3>
 <h4>H4</h4>
 <h5>H5</h5>
 <h6>H6</h6>
 <h1>H1</h1>
 <h2>H2</h2>
 <h3>H3</h3>
 <h4>H4</h4>
 <h5>H5</h5>
 <h6>H6</h6>
 '

C:\inetpub\commonmark\tests\functional\LocalDataTest.php:52

FAILURES!
Tests: 956, Assertions: 1312, Failures: 7.

Generating code coverage report in Clover XML format ... done

Generating code coverage report in HTML format ... done
```

### PR DESCRIPTION
**Pull request by colinodell**
Fixes #189

### CODE REVIEW

**Comment by colinodell** [comment]
Of course I just realized the stdin tests are going to fail on Windows.  Let me see how I can best disable those.

**Comment by colinodell** [comment]
Alright, that test should be skipped now :)

**Comment by garethellis36** [comment]
It no longer hangs when you run it with no STDIN (or with any STDIN for that matter). However...

Tests are failing still. A little debugging suggests it's because of this method below - there is no actual .bat file in the bin folder so it's returning false.

```php
    protected function getPathToCommonmark()
    {
        if (strtoupper(substr(PHP_OS, 0, 3)) === 'WIN') {
            return realpath(__DIR__ . '/../../bin/commonmark.bat');
        }

        return realpath(__DIR__ . '/../../bin/commonmark');
    }
```

**Comment by colinodell** [comment]
Hmm...  according to the Composer documentation, a corresponding `.bat` file should have been created: https://getcomposer.org/doc/articles/vendor-binaries.md#what-about-windows-and-bat-files-

**Comment by garethellis36** [comment]
My understanding of that documentation is that composer would only create the `.bat` file if I install the package as a dependency in another project, not if I'm running `composer install` in the package itself.

I'll just test that theory now...

**Comment by garethellis36** [comment]
Confimed:

```shell
C:\inetpub\test>composer install
Loading composer repositories with package information
Installing dependencies (including require-dev)
  - Installing league/commonmark (dev-bugfix/windows-bin 4af8bfa)
    Cloning 4af8bfaacd198f008fc3954e368a09f2849c1298

Writing lock file
Generating autoload files

C:\inetpub\test>ls
composer.json  composer.lock  vendor

C:\inetpub\test>cd vendor/bin

C:\inetpub\test\vendor\bin>ls
commonmark  commonmark.bat
```

If you change the `getPathToCommonmark()` method so that on Windows it returns `"php " . realpath(__DIR__ . '/../../bin/commonmark');`, this does mean that the bin test can run the script, but two tests in BinTest.php still fail:

```shell
1) League\CommonMark\Tests\Functional\BinTest::testNoArgsOrStdin
Failed asserting that 'Failed without error message: php C:\inetpub\commonmark\bin\commonmark' contains "Usage:".

C:\inetpub\commonmark\tests\functional\BinTest.php:19

2) League\CommonMark\Tests\Functional\BinTest::testUnknownOption
Failed asserting that 'Failed without error message: php C:\inetpub\commonmark\bin\commonmark --foo' contains "Unknown option".

C:\inetpub\commonmark\tests\functional\BinTest.php:58
```

This appears to be because the `Command` object is getting nothing back from stdout or stderr so the expected error message isn't present. I suspect these tests may have to be skipped on Windows as well.

Some tests in `EmphasisTest` also fail, but if you update the `getPathToCommonmark()` method here to match the `BinTest` version, the tests pass.

**Comment by colinodell** [comment]
@garethellis36 Thank you for the detailed feedback!  I have corrected the remaining issues and also added automated Windows testing via AppVeyor to ensure everything works properly.

**Pull request merged**
