### PR TITLE
Unescaped pipe sign hid the errors

### PR DESCRIPTION
**Pull request by szepeviktor**
...of the last 8 months.

Please see [CI output](https://travis-ci.org/thephpleague/commonmark/jobs/620049465).

### CODE REVIEW

**Comment by szepeviktor** [comment]
>   Ignored error pattern #should return string but returns League\\CommonMark\\HtmlElement\|string\.$# was not matched in reported errors.                                          
>  Ignored error pattern #Cannot call method .+ on League\\CommonMark\\Delimiter\\Delimiter\|null\.$# in path src/Delimiter/DelimiterStack.php was not matched in reported errors.  

These two seems to be resolved.

**Comment by colinodell** [comment]
Yikes! Thank you for catching this.

**Comment by szepeviktor** [comment]
Please consider fixing the revealed problem instead of adding them to ignore list.

**Comment by colinodell** [comment]
I've resolved most of the issues that were found.  I've also chosen to ignore some errors, particularly ones about functions not expecting null or false values in cases where I know a `null` or `false` will never be passed, either due to the underlying logic (which phpstan doesn't understand) or when using `preg_` functions and I'm 100% certain there's no error with the regex.

**Comment by szepeviktor** [comment]
All green 🍏

**Comment by szepeviktor** [comment]
> Please enter RIPS-API URL (default: https://api-3.ripstech.com): 

@colinodell this env. var. may be missing

**Comment by colinodell** [comment]
Hmm... it's definitely configured within Travis: 
image  So I'm not sure why it's asking for one here.

**Comment by GrahamCampbell** [comment]
It's because Travis doesn't let PRs see secrets, so someone can't just PR an edit that prints the secret env variables.

**Comment by szepeviktor** [comment]
Thank you.

**Pull request merged**
